export default {
  serverBaseURL: 'http://localhost:3333',
  en: {
    Dashboard: "Dashboard",
    logout: 'Log out',
    myTranspTitle: "My Transportations",
    adminPanelTitle: "Admin panel",
    transps: "Transportations",
    users: "Users",
    transpEmail: 'Tranporter email',
    date: 'Date',
    temp: 'Temperature',
    isValid: 'Is valid?',
    valid: 'Valid',
    invalid: "Invalid",
    minTempSet: 'Min temp set',
    maxTempSet: 'Max temp set',
    certStatus: 'Certificate status',
    notCertified: 'Not certified',
    openCert: 'Open certificate',
    score: "Score",
    genSample: 'Generate one more sample',
    tempProfiles: "Temperature Profiles",
    tempPoints: "Temperature Points",
  }, 
  ua: {
    Dashboard: "Панель управління",
    logout: 'Вийти',
    myTranspTitle: "Мої перевезення",
    adminPanelTitle: "Панель управління",
    transps: "Перевезення",
    users: "Користувачі",
    transpEmail: 'Пошта перевізника',
    date: 'Дата',
    temp: 'Температура',
    isValid: 'Чи з порушеннями?',
    valid: 'Без порушень',
    invalid: "З порушеннями",
    minTempSet: 'Мінімальна дозволена температура',
    maxTempSet: 'Максимальна дозволена температура',
    certStatus: 'Статус сертифікату',
    notCertified: 'У сертифікаті відмовлено',
    openCert: 'Переглянути сертифікат',
    score: "Кількість балів",
    genSample: 'Сгенерувати ще один зразок',
    tempProfiles: "Температурні профілі",
    tempPoints: "Точки температур",
  },
};